# Generated by Django 5.0.6 on 2024-05-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
