# Generated by Django 5.0.6 on 2024-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_options_alter_payment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('cod', 'Cash on Delivery')], default='card', max_length=200),
        ),
    ]
