# Generated by Django 5.0.6 on 2024-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
            },
        ),
    ]
