# Generated by Django 5.0.6 on 2024-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='fullname',
            table='full_names',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
