# Generated by Django 5.0.6 on 2024-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_options_alter_address_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='noHouse',
            new_name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='no_house',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
