# Generated by Django 5.0.6 on 2024-05-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shipping_cost_order_subtotal_order_total'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.shipment'),
        ),
    ]
